web:
  image: nginx
  volumes:
   - nginx.conf:/etc/nginx/nginx.conf
   - default.d:/etc/nginx/default.d
   - conf.d:/etc/nginx/conf.d
   - pelican-output:/usr/share/nginx/html
  ports:
   - "8080:80"
  command: [nginx, '-g', 'daemon off;']
